-- MySQL Script generated by MySQL Workbench
-- mié 29 ene 2020 14:15:15 -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_project_node
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_project_node` ;

-- -----------------------------------------------------
-- Schema db_project_node
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_project_node` DEFAULT CHARACTER SET armscii8 ;
USE `db_project_node` ;

-- -----------------------------------------------------
-- Table `db_project_node`.`rols`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_project_node`.`rols` ;

CREATE TABLE IF NOT EXISTS `db_project_node`.`rols` (
  `rol_id` INT NOT NULL AUTO_INCREMENT,
  `rol_name` VARCHAR(45) NOT NULL,
  `rol_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_project_node`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_project_node`.`users` ;

CREATE TABLE IF NOT EXISTS `db_project_node`.`users` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(45) NOT NULL,
  `rol_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`user_email` ASC),
  INDEX `rol_id_idx` (`rol_id` ASC),
  CONSTRAINT `rol_id`
    FOREIGN KEY (`rol_id`)
    REFERENCES `db_project_node`.`rols` (`rol_id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
